runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /archive
    static_files: archive.html
    upload: archive.html

  - url: /index
    static_files: index.html
    upload: index.html

  - url: /(.*)
    static_files: \1
    upload: (.*)
